// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvrpGeJfQWqe4t9UUmFQMibkaQYwA36U',
    appId: '1:908583080871:web:9bd07e0a5e0817a84fdc82',
    messagingSenderId: '908583080871',
    projectId: 'unieater-561c4',
    authDomain: 'unieater-561c4.firebaseapp.com',
    storageBucket: 'unieater-561c4.appspot.com',
    measurementId: 'G-0KHFQXHQ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEr6JP-QR1JOHjmn0QH-h7UUhc-GJ5O4',
    appId: '1:908583080871:android:f748b8a806f3cdf04fdc82',
    messagingSenderId: '908583080871',
    projectId: 'unieater-561c4',
    storageBucket: 'unieater-561c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fKVcpFH2nsHjUc-WZjtizEWqkvtxDos',
    appId: '1:908583080871:ios:2fcfd5cad4d5d7584fdc82',
    messagingSenderId: '908583080871',
    projectId: 'unieater-561c4',
    storageBucket: 'unieater-561c4.appspot.com',
    iosBundleId: 'com.example.unieater',
  );

}